### ISSUE TITLE
Editing posts & add section

### ISSUE THREAD

**Issue by dakolech** [SuperGrupa/Forum-Steganum#14]

**Comment by Nitrooos** [comment]
Edycji postów nie zrobiłem :P właśnie dlatego, że była na forum-functionality-2
O dodawaniu nowej sekcji zapomniałem - chcę teraz uzupełnić te braki zanim przejdę do kroku "Implement a steganography algorithm"

**Comment by Nitrooos** [comment]
Przeniosłem do "Implement a steganography algorithm", bo chcę uzupełnić te braki przed pójściem dalej

**Comment by dakolech** [comment]
Spoko
