### ISSUE TITLE
CRUD topics

### ISSUE THREAD

**Issue by dakolech** [SuperGrupa/Forum-Steganum#16]

**Comment by Nitrooos** [comment]
w admin panelu chyba nie będzie zarządzania postami, tematami itd? to jest przecież dostępne dla admina na forum normalnie

**Comment by dakolech** [comment]
Powinno być. Jakaś wyszukiwarka, statystyki itp. Lepiej się zarządza w jednym miejscu wszystkim. Ale to później

**Comment by Nitrooos** [comment]
ok, ale żeby się milestony nie rozjechały to chyba dać to do FF-3?

**Comment by dakolech** [comment]
no możesz dać
