### ISSUE TITLE
Create system to hiding some functionality

### ISSUE THREAD

**Issue by dakolech** [SuperGrupa/Forum-Steganum#23]
Use meteor templates instead of ng-if (ng-if is visible in dom as an comment)

**Comment by Nitrooos** [comment]
To chyba też już nieaktualne... daj znać czy chcesz coś tam ukrywać

**Comment by dakolech** [comment]
może ta wtyczka się w to wpisuje

**Comment by Nitrooos** [comment]
jaka wtyczka?

**Comment by dakolech** [comment]
do  "ukrywania" serwisu, ta co zamienia nazwy metod itp

**Comment by Nitrooos** [comment]
ok, chociaż to chyba do też do FF-3, bo pewnie na końcu będzie robione
