### ISSUE TITLE
Refactor client/posts/posts.service.coffee from an A on Code Climate

### ISSUE THREAD

**Issue by dakolech** [SuperGrupa/Forum-Steganum#3]
https://codeclimate.com/github/SuperGrupa/Forum-Steganum/client/posts/posts.service.coffee

**Comment by Nitrooos** [comment]
To jest nadal aktualne? Bo różny poziom wcięć to akurat skaza całego projektu, a nie tylko tego pliku :P

**Comment by dakolech** [comment]
Zrobiłem to żeby sprawdzić funckjonalność code-climate :computer:
