### ISSUE TITLE
Connect sections, topics & posts in one

### ISSUE THREAD

**Issue by Nitrooos** [SuperGrupa/Forum-Steganum#40]

**Comment by dakolech** [comment]
Ty,  in one whole jest niepoprawne :P

**Comment by Nitrooos** [comment]
a jak napisać, że w jedną całość? :P
i w ogóle to chyba niedobrze, że na branchu dotyczącym tylko topiców robię i topici i sections i powoli spajam ze sobą
tego nie da się robić oddzielnie

**Comment by dakolech** [comment]
in one po prostu
