### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by dakolech** [SuperGrupa/Forum-Steganum#67]

**Comment by Nitrooos** [comment]
Jak dokończysz to zadanie (chyba gotowe?) to wrzuć na developa, dopiero potem rób merga na mastera - będziemy mieli 3 milestony do końca: algorytm, ff2, ff3 i może uda się ich znowu trzymać :)

**Comment by dakolech** [comment]
roger that, zostały mi tylko testy na serwerze
